/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(map_display.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(703047722310652a0b3f971b2f77a5ef)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/visualization/map_display.h>
// pydoc.h is automatically generated in the build directory
#include <map_display_pydoc.h>

void bind_map_display(py::module& m)
{

    using map_display    = gr::visualization::map_display;


    py::class_<map_display, gr::block, gr::basic_block,
        std::shared_ptr<map_display>>(m, "map_display", D(map_display))

        .def(py::init(&map_display::make),
           D(map_display,make)
        )
        



        ;




}








